version: "3.4"
services:
  db:
    image: test-server-db
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_pass
      - POSTGRES_DB=test
    ports:
      - 5432:5432
    container_name: test-server-db
  server:
    image: xdu31/test-server:latest
    command:
      - --database.name=test
      - --database.user=test_user
      - --database.password=test_pass
      - --database.address=db
    links:
      - db
    ports:
      - 8081:8081
    container_name: test-server
