apiVersion: v1
kind: ConfigMap
metadata:
  name: testserver-configmap
  namespace: testserver
data:
  DB_HOST: "Host"
  DB_PORT: "PORT"
  DB_NAME: "Name"
  DB_USER: "User"
  DB_PASSWORD: "Password"
  DB_SSLMODE: disable
  DB_RETRIES: "3"
