// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/xdu31/test-server/pkg/pb/service.proto

// Generated with protoc-gen-gorm version: v0.19.0
// Anticipating compatibility with atlas-app-toolkit version: v0.19.2

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	github.com/xdu31/test-server/pkg/pb/service.proto

It has these top-level messages:
	VersionResponse
	Ip
	CreateIpRequest
	CreateIpResponse
	ReadIpRequest
	ReadIpResponse
	UpdateIpRequest
	UpdateIpResponse
	DeleteIpRequest
	DeleteIpResponse
	ListIpsRequest
	ListIpsResponse
*/
package service

import context "context"
import fmt "fmt"

import auth1 "github.com/infobloxopen/atlas-app-toolkit/auth"
import errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
import field_mask1 "google.golang.org/genproto/protobuf/field_mask"
import gorm1 "github.com/jinzhu/gorm"
import gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
import query1 "github.com/infobloxopen/atlas-app-toolkit/query"
import resource1 "github.com/infobloxopen/atlas-app-toolkit/gorm/resource"
import types1 "github.com/infobloxopen/protoc-gen-gorm/types"

import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/lyft/protoc-gen-validate/validate"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "github.com/infobloxopen/atlas-app-toolkit/query"
import _ "github.com/infobloxopen/atlas-app-toolkit/rpc/resource"

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type IpORM struct {
	AccountID string
	Id        int64        `gorm:"type:serial;primary_key"`
	IpAddress *types1.Inet `gorm:"type:varchar(48)"`
}

// TableName overrides the default tablename generated by GORM
func (IpORM) TableName() string {
	return "ips"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *Ip) ToORM(ctx context.Context) (IpORM, error) {
	to := IpORM{}
	var err error
	if prehook, ok := interface{}(m).(IpWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	if v, err := resource1.DecodeInt64(&Ip{}, m.Id); err != nil {
		return to, err
	} else {
		to.Id = v
	}
	if m.IpAddress != nil {
		if to.IpAddress, err = types1.ParseInet(m.IpAddress.Value); err != nil {
			return to, err
		}
	}
	accountID, err := auth1.GetAccountID(ctx, nil)
	if err != nil {
		return to, err
	}
	to.AccountID = accountID
	if posthook, ok := interface{}(m).(IpWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *IpORM) ToPB(ctx context.Context) (Ip, error) {
	to := Ip{}
	var err error
	if prehook, ok := interface{}(m).(IpWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	if v, err := resource1.Encode(&Ip{}, m.Id); err != nil {
		return to, err
	} else {
		to.Id = v
	}
	if m.IpAddress != nil && m.IpAddress.IPNet != nil {
		to.IpAddress = &types1.InetValue{Value: m.IpAddress.String()}
	}
	if posthook, ok := interface{}(m).(IpWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type Ip the arg will be the target, the caller the one being converted from

// IpBeforeToORM called before default ToORM code
type IpWithBeforeToORM interface {
	BeforeToORM(context.Context, *IpORM) error
}

// IpAfterToORM called after default ToORM code
type IpWithAfterToORM interface {
	AfterToORM(context.Context, *IpORM) error
}

// IpBeforeToPB called before default ToPB code
type IpWithBeforeToPB interface {
	BeforeToPB(context.Context, *Ip) error
}

// IpAfterToPB called after default ToPB code
type IpWithAfterToPB interface {
	AfterToPB(context.Context, *Ip) error
}

// DefaultCreateIp executes a basic gorm create call
func DefaultCreateIp(ctx context.Context, in *Ip, db *gorm1.DB) (*Ip, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(IpORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(IpORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type IpORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type IpORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultReadIp executes a basic gorm read call
func DefaultReadIp(ctx context.Context, in *Ip, db *gorm1.DB) (*Ip, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if ormObj.Id == 0 {
		return nil, errors1.EmptyIdError
	}
	if hook, ok := interface{}(&ormObj).(IpORMWithBeforeReadApplyQuery); ok {
		if db, err = hook.BeforeReadApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	if db, err = gorm2.ApplyFieldSelection(ctx, db, nil, &IpORM{}); err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(IpORMWithBeforeReadFind); ok {
		if db, err = hook.BeforeReadFind(ctx, db); err != nil {
			return nil, err
		}
	}
	ormResponse := IpORM{}
	if err = db.Where(&ormObj).First(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormResponse).(IpORMWithAfterReadFind); ok {
		if err = hook.AfterReadFind(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormResponse.ToPB(ctx)
	return &pbResponse, err
}

type IpORMWithBeforeReadApplyQuery interface {
	BeforeReadApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type IpORMWithBeforeReadFind interface {
	BeforeReadFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type IpORMWithAfterReadFind interface {
	AfterReadFind(context.Context, *gorm1.DB) error
}

func DefaultDeleteIp(ctx context.Context, in *Ip, db *gorm1.DB) error {
	if in == nil {
		return errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return err
	}
	if ormObj.Id == 0 {
		return errors1.EmptyIdError
	}
	if hook, ok := interface{}(&ormObj).(IpORMWithBeforeDelete_); ok {
		if db, err = hook.BeforeDelete_(ctx, db); err != nil {
			return err
		}
	}
	err = db.Where(&ormObj).Delete(&IpORM{}).Error
	if err != nil {
		return err
	}
	if hook, ok := interface{}(&ormObj).(IpORMWithAfterDelete_); ok {
		err = hook.AfterDelete_(ctx, db)
	}
	return err
}

type IpORMWithBeforeDelete_ interface {
	BeforeDelete_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type IpORMWithAfterDelete_ interface {
	AfterDelete_(context.Context, *gorm1.DB) error
}

func DefaultDeleteIpSet(ctx context.Context, in []*Ip, db *gorm1.DB) error {
	if in == nil {
		return errors1.NilArgumentError
	}
	var err error
	keys := []int64{}
	for _, obj := range in {
		ormObj, err := obj.ToORM(ctx)
		if err != nil {
			return err
		}
		if ormObj.Id == 0 {
			return errors1.EmptyIdError
		}
		keys = append(keys, ormObj.Id)
	}
	if hook, ok := (interface{}(&IpORM{})).(IpORMWithBeforeDeleteSet); ok {
		if db, err = hook.BeforeDeleteSet(ctx, in, db); err != nil {
			return err
		}
	}
	acctId, err := auth1.GetAccountID(ctx, nil)
	if err != nil {
		return err
	}
	err = db.Where("account_id = ? AND id in (?)", acctId, keys).Delete(&IpORM{}).Error
	if err != nil {
		return err
	}
	if hook, ok := (interface{}(&IpORM{})).(IpORMWithAfterDeleteSet); ok {
		err = hook.AfterDeleteSet(ctx, in, db)
	}
	return err
}

type IpORMWithBeforeDeleteSet interface {
	BeforeDeleteSet(context.Context, []*Ip, *gorm1.DB) (*gorm1.DB, error)
}
type IpORMWithAfterDeleteSet interface {
	AfterDeleteSet(context.Context, []*Ip, *gorm1.DB) error
}

// DefaultStrictUpdateIp clears first level 1:many children and then executes a gorm update call
func DefaultStrictUpdateIp(ctx context.Context, in *Ip, db *gorm1.DB) (*Ip, error) {
	if in == nil {
		return nil, fmt.Errorf("Nil argument to DefaultStrictUpdateIp")
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	accountID, err := auth1.GetAccountID(ctx, nil)
	if err != nil {
		return nil, err
	}
	db = db.Where(map[string]interface{}{"account_id": accountID})
	lockedRow := &IpORM{}
	db.Model(&ormObj).Set("gorm:query_option", "FOR UPDATE").Where("id=?", ormObj.Id).First(lockedRow)
	if hook, ok := interface{}(&ormObj).(IpORMWithBeforeStrictUpdateCleanup); ok {
		if db, err = hook.BeforeStrictUpdateCleanup(ctx, db); err != nil {
			return nil, err
		}
	}
	if hook, ok := interface{}(&ormObj).(IpORMWithBeforeStrictUpdateSave); ok {
		if db, err = hook.BeforeStrictUpdateSave(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Save(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(IpORMWithAfterStrictUpdateSave); ok {
		if err = hook.AfterStrictUpdateSave(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	if err != nil {
		return nil, err
	}
	return &pbResponse, err
}

type IpORMWithBeforeStrictUpdateCleanup interface {
	BeforeStrictUpdateCleanup(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type IpORMWithBeforeStrictUpdateSave interface {
	BeforeStrictUpdateSave(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type IpORMWithAfterStrictUpdateSave interface {
	AfterStrictUpdateSave(context.Context, *gorm1.DB) error
}

// DefaultPatchIp executes a basic gorm update call with patch behavior
func DefaultPatchIp(ctx context.Context, in *Ip, updateMask *field_mask1.FieldMask, db *gorm1.DB) (*Ip, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	var pbObj Ip
	var err error
	if hook, ok := interface{}(&pbObj).(IpWithBeforePatchRead); ok {
		if db, err = hook.BeforePatchRead(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	pbReadRes, err := DefaultReadIp(ctx, &Ip{Id: in.GetId()}, db)
	if err != nil {
		return nil, err
	}
	pbObj = *pbReadRes
	if hook, ok := interface{}(&pbObj).(IpWithBeforePatchApplyFieldMask); ok {
		if db, err = hook.BeforePatchApplyFieldMask(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	if _, err := DefaultApplyFieldMaskIp(ctx, &pbObj, in, updateMask, "", db); err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&pbObj).(IpWithBeforePatchSave); ok {
		if db, err = hook.BeforePatchSave(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := DefaultStrictUpdateIp(ctx, &pbObj, db)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(pbResponse).(IpWithAfterPatchSave); ok {
		if err = hook.AfterPatchSave(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	return pbResponse, nil
}

type IpWithBeforePatchRead interface {
	BeforePatchRead(context.Context, *Ip, *field_mask1.FieldMask, *gorm1.DB) (*gorm1.DB, error)
}
type IpWithBeforePatchApplyFieldMask interface {
	BeforePatchApplyFieldMask(context.Context, *Ip, *field_mask1.FieldMask, *gorm1.DB) (*gorm1.DB, error)
}
type IpWithBeforePatchSave interface {
	BeforePatchSave(context.Context, *Ip, *field_mask1.FieldMask, *gorm1.DB) (*gorm1.DB, error)
}
type IpWithAfterPatchSave interface {
	AfterPatchSave(context.Context, *Ip, *field_mask1.FieldMask, *gorm1.DB) error
}

// DefaultPatchSetIp executes a bulk gorm update call with patch behavior
func DefaultPatchSetIp(ctx context.Context, objects []*Ip, updateMasks []*field_mask1.FieldMask, db *gorm1.DB) ([]*Ip, error) {
	if len(objects) != len(updateMasks) {
		return nil, fmt.Errorf(errors1.BadRepeatedFieldMaskTpl, len(updateMasks), len(objects))
	}

	results := make([]*Ip, 0, len(objects))
	for i, patcher := range objects {
		pbResponse, err := DefaultPatchIp(ctx, patcher, updateMasks[i], db)
		if err != nil {
			return nil, err
		}

		results = append(results, pbResponse)
	}

	return results, nil
}

// DefaultApplyFieldMaskIp patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskIp(ctx context.Context, patchee *Ip, patcher *Ip, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*Ip, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"Id" {
			patchee.Id = patcher.Id
			continue
		}
		if f == prefix+"IpAddress" {
			patchee.IpAddress = patcher.IpAddress
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListIp executes a gorm list call
func DefaultListIp(ctx context.Context, db *gorm1.DB, f *query1.Filtering, s *query1.Sorting, p *query1.Pagination, fs *query1.FieldSelection) ([]*Ip, error) {
	in := Ip{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(IpORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db, f, s, p, fs); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &IpORM{}, &Ip{}, f, s, p, fs)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(IpORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db, f, s, p, fs); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("id")
	ormResponse := []IpORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(IpORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse, f, s, p, fs); err != nil {
			return nil, err
		}
	}
	pbResponse := []*Ip{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type IpORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB, *query1.Filtering, *query1.Sorting, *query1.Pagination, *query1.FieldSelection) (*gorm1.DB, error)
}
type IpORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB, *query1.Filtering, *query1.Sorting, *query1.Pagination, *query1.FieldSelection) (*gorm1.DB, error)
}
type IpORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]IpORM, *query1.Filtering, *query1.Sorting, *query1.Pagination, *query1.FieldSelection) error
}
type IpsDefaultServer struct {
	DB *gorm1.DB
}

// Create ...
func (m *IpsDefaultServer) Create(ctx context.Context, in *CreateIpRequest) (*CreateIpResponse, error) {
	db := m.DB
	if custom, ok := interface{}(in).(IpsIpWithBeforeCreate); ok {
		var err error
		if db, err = custom.BeforeCreate(ctx, db); err != nil {
			return nil, err
		}
	}
	res, err := DefaultCreateIp(ctx, in.GetPayload(), db)
	if err != nil {
		return nil, err
	}
	out := &CreateIpResponse{Result: res}
	if custom, ok := interface{}(in).(IpsIpWithAfterCreate); ok {
		var err error
		if err = custom.AfterCreate(ctx, out, db); err != nil {
			return nil, err
		}
	}
	return out, nil
}

// IpsIpWithBeforeCreate called before DefaultCreateIp in the default Create handler
type IpsIpWithBeforeCreate interface {
	BeforeCreate(context.Context, *gorm1.DB) (*gorm1.DB, error)
}

// IpsIpWithAfterCreate called before DefaultCreateIp in the default Create handler
type IpsIpWithAfterCreate interface {
	AfterCreate(context.Context, *CreateIpResponse, *gorm1.DB) error
}

// Read ...
func (m *IpsDefaultServer) Read(ctx context.Context, in *ReadIpRequest) (*ReadIpResponse, error) {
	db := m.DB
	if custom, ok := interface{}(in).(IpsIpWithBeforeRead); ok {
		var err error
		if db, err = custom.BeforeRead(ctx, db); err != nil {
			return nil, err
		}
	}
	res, err := DefaultReadIp(ctx, &Ip{Id: in.GetId()}, db)
	if err != nil {
		return nil, err
	}
	out := &ReadIpResponse{Result: res}
	if custom, ok := interface{}(in).(IpsIpWithAfterRead); ok {
		var err error
		if err = custom.AfterRead(ctx, out, db); err != nil {
			return nil, err
		}
	}
	return out, nil
}

// IpsIpWithBeforeRead called before DefaultReadIp in the default Read handler
type IpsIpWithBeforeRead interface {
	BeforeRead(context.Context, *gorm1.DB) (*gorm1.DB, error)
}

// IpsIpWithAfterRead called before DefaultReadIp in the default Read handler
type IpsIpWithAfterRead interface {
	AfterRead(context.Context, *ReadIpResponse, *gorm1.DB) error
}

// Update ...
func (m *IpsDefaultServer) Update(ctx context.Context, in *UpdateIpRequest) (*UpdateIpResponse, error) {
	var err error
	var res *Ip
	db := m.DB
	if custom, ok := interface{}(in).(IpsIpWithBeforeUpdate); ok {
		var err error
		if db, err = custom.BeforeUpdate(ctx, db); err != nil {
			return nil, err
		}
	}
	res, err = DefaultStrictUpdateIp(ctx, in.GetPayload(), db)
	if err != nil {
		return nil, err
	}
	out := &UpdateIpResponse{Result: res}
	if custom, ok := interface{}(in).(IpsIpWithAfterUpdate); ok {
		var err error
		if err = custom.AfterUpdate(ctx, out, db); err != nil {
			return nil, err
		}
	}
	return out, nil
}

// IpsIpWithBeforeUpdate called before DefaultUpdateIp in the default Update handler
type IpsIpWithBeforeUpdate interface {
	BeforeUpdate(context.Context, *gorm1.DB) (*gorm1.DB, error)
}

// IpsIpWithAfterUpdate called before DefaultUpdateIp in the default Update handler
type IpsIpWithAfterUpdate interface {
	AfterUpdate(context.Context, *UpdateIpResponse, *gorm1.DB) error
}

// Delete ...
func (m *IpsDefaultServer) Delete(ctx context.Context, in *DeleteIpRequest) (*DeleteIpResponse, error) {
	db := m.DB
	if custom, ok := interface{}(in).(IpsIpWithBeforeDelete); ok {
		var err error
		if db, err = custom.BeforeDelete(ctx, db); err != nil {
			return nil, err
		}
	}
	err := DefaultDeleteIp(ctx, &Ip{Id: in.GetId()}, db)
	if err != nil {
		return nil, err
	}
	out := &DeleteIpResponse{}
	if custom, ok := interface{}(in).(IpsIpWithAfterDelete); ok {
		var err error
		if err = custom.AfterDelete(ctx, out, db); err != nil {
			return nil, err
		}
	}
	return out, nil
}

// IpsIpWithBeforeDelete called before DefaultDeleteIp in the default Delete handler
type IpsIpWithBeforeDelete interface {
	BeforeDelete(context.Context, *gorm1.DB) (*gorm1.DB, error)
}

// IpsIpWithAfterDelete called before DefaultDeleteIp in the default Delete handler
type IpsIpWithAfterDelete interface {
	AfterDelete(context.Context, *DeleteIpResponse, *gorm1.DB) error
}

// List ...
func (m *IpsDefaultServer) List(ctx context.Context, in *ListIpsRequest) (*ListIpsResponse, error) {
	db := m.DB
	if custom, ok := interface{}(in).(IpsIpWithBeforeList); ok {
		var err error
		if db, err = custom.BeforeList(ctx, db); err != nil {
			return nil, err
		}
	}
	res, err := DefaultListIp(ctx, db, in.Filter, in.OrderBy, in.Paging, in.Fields)
	if err != nil {
		return nil, err
	}
	out := &ListIpsResponse{Results: res}
	if custom, ok := interface{}(in).(IpsIpWithAfterList); ok {
		var err error
		if err = custom.AfterList(ctx, out, db); err != nil {
			return nil, err
		}
	}
	return out, nil
}

// IpsIpWithBeforeList called before DefaultListIp in the default List handler
type IpsIpWithBeforeList interface {
	BeforeList(context.Context, *gorm1.DB) (*gorm1.DB, error)
}

// IpsIpWithAfterList called before DefaultListIp in the default List handler
type IpsIpWithAfterList interface {
	AfterList(context.Context, *ListIpsResponse, *gorm1.DB) error
}
