// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/xdu31/test-server/pkg/pb/service.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	query "github.com/infobloxopen/atlas-app-toolkit/query"
	resource "github.com/infobloxopen/atlas-app-toolkit/rpc/resource"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	types "github.com/infobloxopen/protoc-gen-gorm/types"
	_ "github.com/lyft/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TODO: Structure your own protobuf messages. Each protocol buffer message is a
// small logical record of information, containing a series of name-value pairs.
type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6170c2a13e50b4a9, []int{0}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// TypeWithID demonstrates some basic assocation behavior
type Ip struct {
	// any field named 'id' is assumed by gorm to be the primary key for the
	// object.
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IpAddress            *types.InetValue     `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Ip) Reset()         { *m = Ip{} }
func (m *Ip) String() string { return proto.CompactTextString(m) }
func (*Ip) ProtoMessage()    {}
func (*Ip) Descriptor() ([]byte, []int) {
	return fileDescriptor_6170c2a13e50b4a9, []int{1}
}

func (m *Ip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ip.Unmarshal(m, b)
}
func (m *Ip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ip.Marshal(b, m, deterministic)
}
func (m *Ip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ip.Merge(m, src)
}
func (m *Ip) XXX_Size() int {
	return xxx_messageInfo_Ip.Size(m)
}
func (m *Ip) XXX_DiscardUnknown() {
	xxx_messageInfo_Ip.DiscardUnknown(m)
}

var xxx_messageInfo_Ip proto.InternalMessageInfo

func (m *Ip) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Ip) GetIpAddress() *types.InetValue {
	if m != nil {
		return m.IpAddress
	}
	return nil
}

type CreateIpRequest struct {
	Payload              *Ip      `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateIpRequest) Reset()         { *m = CreateIpRequest{} }
func (m *CreateIpRequest) String() string { return proto.CompactTextString(m) }
func (*CreateIpRequest) ProtoMessage()    {}
func (*CreateIpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6170c2a13e50b4a9, []int{2}
}

func (m *CreateIpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIpRequest.Unmarshal(m, b)
}
func (m *CreateIpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIpRequest.Marshal(b, m, deterministic)
}
func (m *CreateIpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIpRequest.Merge(m, src)
}
func (m *CreateIpRequest) XXX_Size() int {
	return xxx_messageInfo_CreateIpRequest.Size(m)
}
func (m *CreateIpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIpRequest proto.InternalMessageInfo

func (m *CreateIpRequest) GetPayload() *Ip {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateIpResponse struct {
	Result               *Ip      `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateIpResponse) Reset()         { *m = CreateIpResponse{} }
func (m *CreateIpResponse) String() string { return proto.CompactTextString(m) }
func (*CreateIpResponse) ProtoMessage()    {}
func (*CreateIpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6170c2a13e50b4a9, []int{3}
}

func (m *CreateIpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIpResponse.Unmarshal(m, b)
}
func (m *CreateIpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIpResponse.Marshal(b, m, deterministic)
}
func (m *CreateIpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIpResponse.Merge(m, src)
}
func (m *CreateIpResponse) XXX_Size() int {
	return xxx_messageInfo_CreateIpResponse.Size(m)
}
func (m *CreateIpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIpResponse proto.InternalMessageInfo

func (m *CreateIpResponse) GetResult() *Ip {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadIpRequest struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReadIpRequest) Reset()         { *m = ReadIpRequest{} }
func (m *ReadIpRequest) String() string { return proto.CompactTextString(m) }
func (*ReadIpRequest) ProtoMessage()    {}
func (*ReadIpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6170c2a13e50b4a9, []int{4}
}

func (m *ReadIpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadIpRequest.Unmarshal(m, b)
}
func (m *ReadIpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadIpRequest.Marshal(b, m, deterministic)
}
func (m *ReadIpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadIpRequest.Merge(m, src)
}
func (m *ReadIpRequest) XXX_Size() int {
	return xxx_messageInfo_ReadIpRequest.Size(m)
}
func (m *ReadIpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadIpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadIpRequest proto.InternalMessageInfo

func (m *ReadIpRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type ReadIpResponse struct {
	Result               *Ip      `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadIpResponse) Reset()         { *m = ReadIpResponse{} }
func (m *ReadIpResponse) String() string { return proto.CompactTextString(m) }
func (*ReadIpResponse) ProtoMessage()    {}
func (*ReadIpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6170c2a13e50b4a9, []int{5}
}

func (m *ReadIpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadIpResponse.Unmarshal(m, b)
}
func (m *ReadIpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadIpResponse.Marshal(b, m, deterministic)
}
func (m *ReadIpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadIpResponse.Merge(m, src)
}
func (m *ReadIpResponse) XXX_Size() int {
	return xxx_messageInfo_ReadIpResponse.Size(m)
}
func (m *ReadIpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadIpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadIpResponse proto.InternalMessageInfo

func (m *ReadIpResponse) GetResult() *Ip {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateIpRequest struct {
	Payload              *Ip      `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateIpRequest) Reset()         { *m = UpdateIpRequest{} }
func (m *UpdateIpRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateIpRequest) ProtoMessage()    {}
func (*UpdateIpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6170c2a13e50b4a9, []int{6}
}

func (m *UpdateIpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateIpRequest.Unmarshal(m, b)
}
func (m *UpdateIpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateIpRequest.Marshal(b, m, deterministic)
}
func (m *UpdateIpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateIpRequest.Merge(m, src)
}
func (m *UpdateIpRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateIpRequest.Size(m)
}
func (m *UpdateIpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateIpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateIpRequest proto.InternalMessageInfo

func (m *UpdateIpRequest) GetPayload() *Ip {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateIpResponse struct {
	Result               *Ip      `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateIpResponse) Reset()         { *m = UpdateIpResponse{} }
func (m *UpdateIpResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateIpResponse) ProtoMessage()    {}
func (*UpdateIpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6170c2a13e50b4a9, []int{7}
}

func (m *UpdateIpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateIpResponse.Unmarshal(m, b)
}
func (m *UpdateIpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateIpResponse.Marshal(b, m, deterministic)
}
func (m *UpdateIpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateIpResponse.Merge(m, src)
}
func (m *UpdateIpResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateIpResponse.Size(m)
}
func (m *UpdateIpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateIpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateIpResponse proto.InternalMessageInfo

func (m *UpdateIpResponse) GetResult() *Ip {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteIpRequest struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteIpRequest) Reset()         { *m = DeleteIpRequest{} }
func (m *DeleteIpRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteIpRequest) ProtoMessage()    {}
func (*DeleteIpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6170c2a13e50b4a9, []int{8}
}

func (m *DeleteIpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteIpRequest.Unmarshal(m, b)
}
func (m *DeleteIpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteIpRequest.Marshal(b, m, deterministic)
}
func (m *DeleteIpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteIpRequest.Merge(m, src)
}
func (m *DeleteIpRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteIpRequest.Size(m)
}
func (m *DeleteIpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteIpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteIpRequest proto.InternalMessageInfo

func (m *DeleteIpRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type DeleteIpResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteIpResponse) Reset()         { *m = DeleteIpResponse{} }
func (m *DeleteIpResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteIpResponse) ProtoMessage()    {}
func (*DeleteIpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6170c2a13e50b4a9, []int{9}
}

func (m *DeleteIpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteIpResponse.Unmarshal(m, b)
}
func (m *DeleteIpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteIpResponse.Marshal(b, m, deterministic)
}
func (m *DeleteIpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteIpResponse.Merge(m, src)
}
func (m *DeleteIpResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteIpResponse.Size(m)
}
func (m *DeleteIpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteIpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteIpResponse proto.InternalMessageInfo

type ListIpsRequest struct {
	Filter               *query.Filtering      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy              *query.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	Paging               *query.Pagination     `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListIpsRequest) Reset()         { *m = ListIpsRequest{} }
func (m *ListIpsRequest) String() string { return proto.CompactTextString(m) }
func (*ListIpsRequest) ProtoMessage()    {}
func (*ListIpsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6170c2a13e50b4a9, []int{10}
}

func (m *ListIpsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListIpsRequest.Unmarshal(m, b)
}
func (m *ListIpsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListIpsRequest.Marshal(b, m, deterministic)
}
func (m *ListIpsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListIpsRequest.Merge(m, src)
}
func (m *ListIpsRequest) XXX_Size() int {
	return xxx_messageInfo_ListIpsRequest.Size(m)
}
func (m *ListIpsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListIpsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListIpsRequest proto.InternalMessageInfo

func (m *ListIpsRequest) GetFilter() *query.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListIpsRequest) GetOrderBy() *query.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListIpsRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListIpsRequest) GetPaging() *query.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListIpsResponse struct {
	Results              []*Ip    `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListIpsResponse) Reset()         { *m = ListIpsResponse{} }
func (m *ListIpsResponse) String() string { return proto.CompactTextString(m) }
func (*ListIpsResponse) ProtoMessage()    {}
func (*ListIpsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6170c2a13e50b4a9, []int{11}
}

func (m *ListIpsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListIpsResponse.Unmarshal(m, b)
}
func (m *ListIpsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListIpsResponse.Marshal(b, m, deterministic)
}
func (m *ListIpsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListIpsResponse.Merge(m, src)
}
func (m *ListIpsResponse) XXX_Size() int {
	return xxx_messageInfo_ListIpsResponse.Size(m)
}
func (m *ListIpsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListIpsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListIpsResponse proto.InternalMessageInfo

func (m *ListIpsResponse) GetResults() []*Ip {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*VersionResponse)(nil), "service.VersionResponse")
	proto.RegisterType((*Ip)(nil), "service.Ip")
	proto.RegisterType((*CreateIpRequest)(nil), "service.CreateIpRequest")
	proto.RegisterType((*CreateIpResponse)(nil), "service.CreateIpResponse")
	proto.RegisterType((*ReadIpRequest)(nil), "service.ReadIpRequest")
	proto.RegisterType((*ReadIpResponse)(nil), "service.ReadIpResponse")
	proto.RegisterType((*UpdateIpRequest)(nil), "service.UpdateIpRequest")
	proto.RegisterType((*UpdateIpResponse)(nil), "service.UpdateIpResponse")
	proto.RegisterType((*DeleteIpRequest)(nil), "service.DeleteIpRequest")
	proto.RegisterType((*DeleteIpResponse)(nil), "service.DeleteIpResponse")
	proto.RegisterType((*ListIpsRequest)(nil), "service.ListIpsRequest")
	proto.RegisterType((*ListIpsResponse)(nil), "service.ListIpsResponse")
}

func init() {
	proto.RegisterFile("github.com/xdu31/test-server/pkg/pb/service.proto", fileDescriptor_6170c2a13e50b4a9)
}

var fileDescriptor_6170c2a13e50b4a9 = []byte{
	// 811 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xc1, 0x6e, 0x1b, 0x37,
	0x10, 0x85, 0x64, 0x61, 0xa5, 0x4c, 0xd2, 0xd8, 0x20, 0xe0, 0x58, 0x56, 0x13, 0xc0, 0xd8, 0xc2,
	0x80, 0xd1, 0x56, 0xcb, 0xc4, 0x49, 0x9b, 0xd4, 0x3d, 0x35, 0x6d, 0x1a, 0xa8, 0xe8, 0x21, 0x58,
	0xa7, 0x3e, 0xd6, 0xa0, 0xb4, 0xa3, 0x2d, 0x11, 0x7a, 0xc9, 0x90, 0x94, 0x1b, 0xa1, 0xc8, 0xa5,
	0xbf, 0xd0, 0xaf, 0xb1, 0x7f, 0xa3, 0xa7, 0xa2, 0xd7, 0x7e, 0x48, 0xb1, 0x24, 0x57, 0x5a, 0xad,
	0x1c, 0xd4, 0xee, 0x45, 0x10, 0x39, 0xf3, 0xde, 0xe3, 0xcc, 0xbe, 0x19, 0x78, 0x94, 0x73, 0xfb,
	0xcb, 0x6c, 0x9c, 0x4c, 0xe4, 0x19, 0x7d, 0x97, 0xcd, 0x1e, 0x3f, 0xa2, 0x16, 0x8d, 0x1d, 0x1a,
	0xd4, 0xe7, 0xa8, 0xa9, 0x7a, 0x93, 0x53, 0x35, 0xa6, 0xe5, 0x89, 0x4f, 0x30, 0x51, 0x5a, 0x5a,
	0x49, 0xba, 0xe1, 0x38, 0xf8, 0x38, 0x97, 0x32, 0x17, 0x48, 0xdd, 0xf5, 0x78, 0x36, 0xa5, 0x78,
	0xa6, 0xec, 0xdc, 0x67, 0x0d, 0xee, 0x87, 0x20, 0x53, 0x9c, 0xb2, 0xa2, 0x90, 0x96, 0x59, 0x2e,
	0x0b, 0x13, 0xa2, 0x5f, 0xd7, 0x64, 0xc5, 0x7c, 0x6a, 0x3d, 0xc7, 0x64, 0x98, 0x63, 0x31, 0x3c,
	0x67, 0x82, 0x67, 0xcc, 0x22, 0x5d, 0xfb, 0x13, 0xc0, 0x9f, 0xd7, 0x92, 0xcd, 0xaf, 0x2c, 0xcf,
	0x51, 0x53, 0xa9, 0x1c, 0xfd, 0x15, 0x52, 0x47, 0x35, 0x29, 0x5e, 0x4c, 0xe5, 0x58, 0xc8, 0x77,
	0x52, 0x61, 0x51, 0x97, 0xcc, 0xa5, 0x3e, 0x5b, 0x50, 0x94, 0x87, 0x80, 0xfd, 0xea, 0xba, 0x58,
	0x3b, 0x57, 0x68, 0xfc, 0x6f, 0x80, 0xfe, 0xf0, 0x21, 0x28, 0xb3, 0x82, 0x99, 0x21, 0x53, 0x6a,
	0x68, 0xa5, 0x14, 0x6f, 0xb8, 0xa5, 0x6f, 0x67, 0xa8, 0xe7, 0x74, 0x22, 0x85, 0xc0, 0x49, 0xf9,
	0x84, 0x53, 0xa9, 0x50, 0x33, 0x2b, 0x75, 0xc5, 0xf5, 0xe2, 0xfa, 0x5c, 0x5a, 0x4d, 0xa8, 0x46,
	0x23, 0x67, 0x7a, 0x82, 0x8b, 0x3f, 0x9e, 0x26, 0xfe, 0x0c, 0x36, 0x4f, 0x50, 0x1b, 0x2e, 0x8b,
	0x14, 0x8d, 0x92, 0x85, 0x41, 0xd2, 0x87, 0xee, 0xb9, 0xbf, 0xea, 0xb7, 0xf6, 0x5a, 0x07, 0xb7,
	0xd2, 0xea, 0x18, 0xbf, 0x87, 0xf6, 0x48, 0x91, 0xa7, 0xd0, 0xe6, 0x99, 0x0b, 0xdd, 0x3e, 0xdc,
	0x4e, 0x9c, 0x5c, 0xa2, 0xd5, 0x24, 0x19, 0x65, 0x58, 0x58, 0x3e, 0xe5, 0xa8, 0x9f, 0x6f, 0x5d,
	0x5e, 0xec, 0xde, 0x01, 0x20, 0x91, 0x41, 0xcd, 0x99, 0x38, 0x68, 0xa5, 0x6d, 0x9e, 0x91, 0x27,
	0x00, 0x5c, 0x9d, 0xb2, 0x2c, 0xd3, 0x68, 0x4c, 0xbf, 0x1d, 0x08, 0x5c, 0x6b, 0x7d, 0x97, 0x46,
	0x05, 0xda, 0x13, 0x26, 0x66, 0x98, 0xde, 0xe2, 0xea, 0x1b, 0x9f, 0x77, 0xd4, 0xbb, 0xbc, 0xd8,
	0xed, 0xf4, 0x5a, 0x7b, 0xad, 0xf8, 0x19, 0x6c, 0x7e, 0xab, 0x91, 0x59, 0x1c, 0xa9, 0x14, 0xdf,
	0xce, 0xd0, 0x58, 0xb2, 0x0f, 0x5d, 0xc5, 0xe6, 0x42, 0xb2, 0xea, 0x41, 0xb7, 0x93, 0xca, 0x98,
	0x23, 0x95, 0x56, 0xb1, 0xf8, 0x29, 0x6c, 0x2d, 0x91, 0xa1, 0xcc, 0x4f, 0x20, 0xd2, 0x68, 0x66,
	0xc2, 0x5e, 0x85, 0x0c, 0xa1, 0xf8, 0x4b, 0xf8, 0x28, 0x45, 0x96, 0xd5, 0x05, 0xff, 0xab, 0xf8,
	0xb2, 0xd4, 0xf8, 0x0b, 0xb8, 0x5b, 0xe1, 0x6e, 0x22, 0xf7, 0x0c, 0x36, 0x7f, 0x52, 0xd9, 0xff,
	0xac, 0x70, 0x89, 0xbc, 0xa1, 0xe4, 0x77, 0x28, 0x70, 0x55, 0xf2, 0x5a, 0x35, 0x12, 0xd8, 0x5a,
	0x22, 0xbd, 0x64, 0xfc, 0x77, 0x0b, 0xee, 0xfe, 0xc8, 0x8d, 0x1d, 0x29, 0x53, 0xb1, 0x51, 0x88,
	0xa6, 0x5c, 0x58, 0xd4, 0x81, 0x71, 0x27, 0xa9, 0xec, 0x9a, 0x30, 0xc5, 0x93, 0xef, 0x5d, 0x8c,
	0x17, 0x79, 0x1a, 0xd2, 0xc8, 0x43, 0xe8, 0x49, 0x9d, 0xa1, 0x3e, 0x1d, 0xcf, 0x17, 0x26, 0x59,
	0x81, 0x1c, 0x4b, 0x6d, 0x4b, 0x40, 0xd7, 0xa5, 0x3d, 0x9f, 0x93, 0x27, 0xa5, 0x04, 0x8a, 0xcc,
	0xf4, 0x37, 0x5c, 0xfe, 0xfd, 0xa6, 0x04, 0x8a, 0xec, 0x18, 0xc3, 0x24, 0xa5, 0x21, 0x97, 0x3c,
	0x84, 0x48, 0xb1, 0x9c, 0x17, 0x79, 0xbf, 0xe3, 0x50, 0xfd, 0x55, 0xd4, 0xab, 0x32, 0xc6, 0x3c,
	0xc2, 0xe7, 0x95, 0xbd, 0x5a, 0x14, 0x17, 0x7a, 0xbc, 0x0f, 0x5d, 0xdf, 0x48, 0xd3, 0x6f, 0xed,
	0x6d, 0xac, 0x7d, 0x9e, 0x10, 0x3b, 0xfc, 0x19, 0xe0, 0x35, 0x1a, 0x7b, 0xec, 0x56, 0x28, 0x79,
	0x05, 0xf0, 0x12, 0x6d, 0x98, 0x3b, 0x72, 0x2f, 0xf1, 0x6b, 0x31, 0xa9, 0x76, 0x66, 0xf2, 0xa2,
	0xdc, 0x99, 0x83, 0xfe, 0x82, 0xa9, 0x31, 0xa1, 0xf1, 0xd6, 0xef, 0x7f, 0xfe, 0xf3, 0x47, 0x1b,
	0x48, 0x8f, 0x86, 0xc9, 0x3c, 0xfc, 0x6b, 0x03, 0x36, 0x46, 0xca, 0x90, 0xd7, 0x10, 0x79, 0xa3,
	0x93, 0x25, 0xba, 0x31, 0x33, 0x83, 0xdd, 0x2b, 0x22, 0x81, 0x78, 0xdb, 0x11, 0x6f, 0xc6, 0x1d,
	0xca, 0x95, 0x39, 0xaa, 0xcc, 0x45, 0x4e, 0xa0, 0x53, 0xba, 0x99, 0xdc, 0x5b, 0x20, 0x57, 0x86,
	0x62, 0xb0, 0xb3, 0x76, 0x1f, 0xf8, 0x1e, 0x38, 0xbe, 0x1d, 0xb2, 0x5d, 0xf2, 0xd1, 0xdf, 0x78,
	0x96, 0x54, 0xeb, 0xe7, 0x94, 0x67, 0xef, 0xc9, 0x19, 0x44, 0xde, 0xb4, 0xb5, 0xd7, 0x36, 0xfc,
	0x5f, 0x7b, 0x6d, 0xd3, 0xdf, 0x71, 0xe2, 0xd8, 0x0f, 0x06, 0x0f, 0x3c, 0x7b, 0x78, 0x6d, 0xd2,
	0x50, 0x59, 0x96, 0x91, 0x41, 0xe4, 0x0d, 0x5b, 0x93, 0x6b, 0x78, 0xbf, 0x26, 0xb7, 0xe6, 0xed,
	0xfd, 0x72, 0x11, 0x95, 0x1b, 0xd0, 0x17, 0xf5, 0xe9, 0x07, 0x8a, 0x7a, 0x09, 0x9d, 0xd2, 0x24,
	0x64, 0xd9, 0x94, 0xd5, 0x81, 0xa8, 0x7d, 0xd7, 0x86, 0x99, 0xe2, 0x3b, 0x8e, 0x39, 0x22, 0xae,
	0xfd, 0x83, 0xe8, 0xf2, 0x62, 0xb7, 0xdd, 0x6b, 0x8d, 0x23, 0xe7, 0x8b, 0xc7, 0xff, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x6b, 0xb1, 0x37, 0x3e, 0x97, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestServerClient is the client API for TestServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestServerClient interface {
	GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type testServerClient struct {
	cc *grpc.ClientConn
}

func NewTestServerClient(cc *grpc.ClientConn) TestServerClient {
	return &testServerClient{cc}
}

func (c *testServerClient) GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/service.TestServer/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServerServer is the server API for TestServer service.
type TestServerServer interface {
	GetVersion(context.Context, *empty.Empty) (*VersionResponse, error)
}

func RegisterTestServerServer(s *grpc.Server, srv TestServerServer) {
	s.RegisterService(&_TestServer_serviceDesc, srv)
}

func _TestServer_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServerServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.TestServer/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServerServer).GetVersion(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _TestServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.TestServer",
	HandlerType: (*TestServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _TestServer_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/xdu31/test-server/pkg/pb/service.proto",
}

// IpsClient is the client API for Ips service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IpsClient interface {
	Create(ctx context.Context, in *CreateIpRequest, opts ...grpc.CallOption) (*CreateIpResponse, error)
	Read(ctx context.Context, in *ReadIpRequest, opts ...grpc.CallOption) (*ReadIpResponse, error)
	Update(ctx context.Context, in *UpdateIpRequest, opts ...grpc.CallOption) (*UpdateIpResponse, error)
	Delete(ctx context.Context, in *DeleteIpRequest, opts ...grpc.CallOption) (*DeleteIpResponse, error)
	List(ctx context.Context, in *ListIpsRequest, opts ...grpc.CallOption) (*ListIpsResponse, error)
}

type ipsClient struct {
	cc *grpc.ClientConn
}

func NewIpsClient(cc *grpc.ClientConn) IpsClient {
	return &ipsClient{cc}
}

func (c *ipsClient) Create(ctx context.Context, in *CreateIpRequest, opts ...grpc.CallOption) (*CreateIpResponse, error) {
	out := new(CreateIpResponse)
	err := c.cc.Invoke(ctx, "/service.Ips/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipsClient) Read(ctx context.Context, in *ReadIpRequest, opts ...grpc.CallOption) (*ReadIpResponse, error) {
	out := new(ReadIpResponse)
	err := c.cc.Invoke(ctx, "/service.Ips/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipsClient) Update(ctx context.Context, in *UpdateIpRequest, opts ...grpc.CallOption) (*UpdateIpResponse, error) {
	out := new(UpdateIpResponse)
	err := c.cc.Invoke(ctx, "/service.Ips/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipsClient) Delete(ctx context.Context, in *DeleteIpRequest, opts ...grpc.CallOption) (*DeleteIpResponse, error) {
	out := new(DeleteIpResponse)
	err := c.cc.Invoke(ctx, "/service.Ips/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipsClient) List(ctx context.Context, in *ListIpsRequest, opts ...grpc.CallOption) (*ListIpsResponse, error) {
	out := new(ListIpsResponse)
	err := c.cc.Invoke(ctx, "/service.Ips/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IpsServer is the server API for Ips service.
type IpsServer interface {
	Create(context.Context, *CreateIpRequest) (*CreateIpResponse, error)
	Read(context.Context, *ReadIpRequest) (*ReadIpResponse, error)
	Update(context.Context, *UpdateIpRequest) (*UpdateIpResponse, error)
	Delete(context.Context, *DeleteIpRequest) (*DeleteIpResponse, error)
	List(context.Context, *ListIpsRequest) (*ListIpsResponse, error)
}

func RegisterIpsServer(s *grpc.Server, srv IpsServer) {
	s.RegisterService(&_Ips_serviceDesc, srv)
}

func _Ips_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Ips/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpsServer).Create(ctx, req.(*CreateIpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ips_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadIpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Ips/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpsServer).Read(ctx, req.(*ReadIpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ips_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Ips/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpsServer).Update(ctx, req.(*UpdateIpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ips_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Ips/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpsServer).Delete(ctx, req.(*DeleteIpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ips_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Ips/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpsServer).List(ctx, req.(*ListIpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ips_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Ips",
	HandlerType: (*IpsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Ips_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Ips_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Ips_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Ips_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Ips_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/xdu31/test-server/pkg/pb/service.proto",
}
